[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
tracing = "0.1.41"
regex = "1.11.1"
lazy_static = "1.5.0"
async-trait = "0.1.86"

[dev-dependencies]
mockall = "0.13.1"
tokio = { version = "1.43.0", features = ["full"] }