[workspace]
members = [
    "application",
    "domain",
    "infrastructure",
    "runner"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.216", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
